import type { Component } from 'svelte';
import {
	Ad,
	Ae,
	Af,
	Ag,
	Ai,
	Al,
	Am,
	Ao,
	Aq,
	Ar,
	At,
	Au,
	Aw,
	Az,
	Ba,
	Bb,
	Bd,
	Be,
	Bf,
	Bg,
	Bh,
	Bi,
	Bj,
	Bl,
	Bm,
	Bn,
	Bo,
	Bq,
	Br,
	Bs,
	Bt,
	Bv,
	Bw,
	By,
	Bz,
	Ca,
	Cc,
	Cd,
	Cf,
	Cg,
	Ch,
	Ci,
	Ck,
	Cl,
	Cm,
	Cn,
	Co,
	Cr,
	Cu,
	Cv,
	Cw,
	Cx,
	Cy,
	Cz,
	De,
	Dj,
	Dk,
	Dm,
	Do,
	Dz,
	Ec,
	Ee,
	Eg,
	Eh,
	Er,
	Es,
	Et,
	Fi,
	Fj,
	Fk,
	Fm,
	Fo,
	Fr,
	Ga,
	Gb,
	Gd,
	Ge,
	Gf,
	Gg,
	Gh,
	Gi,
	Gl,
	Gm,
	Gn,
	Gp,
	Gq,
	Gr,
	Gs,
	Gt,
	Gu,
	Gw,
	Gy,
	Hk,
	Hm,
	Hn,
	Hr,
	Ht,
	Hu,
	Id,
	Ie,
	Il,
	Im,
	In,
	Io,
	Iq,
	Ir,
	Is,
	It,
	Je,
	Jm,
	Jo,
	Jp,
	Ke,
	Kg,
	Kh,
	Ki,
	Km,
	Kn,
	Kp,
	Kr,
	Kw,
	Ky,
	Kz,
	La,
	Lb,
	Lc,
	Li,
	Lk,
	Lr,
	Ls,
	Lt,
	Lu,
	Lv,
	Ly,
	Ma,
	Mc,
	Md,
	Me,
	Mf,
	Mg,
	Mh,
	Mk,
	Ml,
	Mm,
	Mn,
	Mo,
	Mp,
	Mq,
	Mr,
	Ms,
	Mt,
	Mu,
	Mv,
	Mw,
	Mx,
	My,
	Mz,
	Na,
	Nc,
	Ne,
	Nf,
	Ng,
	Ni,
	Nl,
	No,
	Np,
	Nr,
	Nu,
	Nz,
	Om,
	Pa,
	Pe,
	Pf,
	Pg,
	Ph,
	Pk,
	Pl,
	Pm,
	Pn,
	Pr,
	Ps,
	Pt,
	Pw,
	Py,
	Qa,
	Re,
	Ro,
	Rs,
	Ru,
	Rw,
	Sa,
	Sb,
	Sc,
	Sd,
	Se,
	Sg,
	Sh,
	Si,
	Sj,
	Sk,
	Sl,
	Sm,
	Sn,
	So,
	Sr,
	Ss,
	St,
	Sv,
	Sx,
	Sy,
	Sz,
	Tc,
	Td,
	Tf,
	Tg,
	Th,
	Tj,
	Tk,
	Tl,
	Tm,
	Tn,
	To,
	Tr,
	Tt,
	Tv,
	Tw,
	Tz,
	Ua,
	Ug,
	Um,
	Us,
	Uy,
	Uz,
	Va,
	Vc,
	Ve,
	Vg,
	Vi,
	Vn,
	Vu,
	Wf,
	Ws,
	Ye,
	Yt,
	Za,
	Zm,
	Zw
} from 'svelte-flag-icons';

export type Country = {
	name: string;
	iso: string;
	flag: Component;
};

const COUNTRY_BY_ISO_MAP: Record<string, Country> = {
	AF: { iso: 'AF', name: 'Afghanistan', flag: Af },
	AL: { iso: 'AL', name: 'Albania', flag: Al },
	DZ: { iso: 'DZ', name: 'Algeria', flag: Dz },
	AD: { iso: 'AD', name: 'Andorra', flag: Ad },
	AO: { iso: 'AO', name: 'Angola', flag: Ao },
	AI: { iso: 'AI', name: 'Anguilla', flag: Ai },
	AQ: { iso: 'AQ', name: 'Antarctica', flag: Aq },
	AG: { iso: 'AG', name: 'Antigua and Barbuda', flag: Ag },
	AR: { iso: 'AR', name: 'Argentina', flag: Ar },
	AM: { iso: 'AM', name: 'Armenia', flag: Am },
	AW: { iso: 'AW', name: 'Aruba', flag: Aw },
	AU: { iso: 'AU', name: 'Australia', flag: Au },
	AT: { iso: 'AT', name: 'Austria', flag: At },
	AZ: { iso: 'AZ', name: 'Azerbaijan', flag: Az },
	BS: { iso: 'BS', name: 'Bahamas', flag: Bs },
	BH: { iso: 'BH', name: 'Bahrain', flag: Bh },
	BD: { iso: 'BD', name: 'Bangladesh', flag: Bd },
	BB: { iso: 'BB', name: 'Barbados', flag: Bb },
	BY: { iso: 'BY', name: 'Belarus', flag: By },
	BE: { iso: 'BE', name: 'Belgium', flag: Be },
	BZ: { iso: 'BZ', name: 'Belize', flag: Bz },
	BJ: { iso: 'BJ', name: 'Benin', flag: Bj },
	BM: { iso: 'BM', name: 'Bermuda', flag: Bm },
	BT: { iso: 'BT', name: 'Bhutan', flag: Bt },
	BO: { iso: 'BO', name: 'Bolivia', flag: Bo },
	BQ: { iso: 'BQ', name: 'Bonaire, Sint Eustatius and Saba', flag: Bq },
	BA: { iso: 'BA', name: 'Bosnia and Herzegovina', flag: Ba },
	BW: { iso: 'BW', name: 'Botswana', flag: Bw },
	BV: { iso: 'BV', name: 'Bouvet Island', flag: Bv },
	BR: { iso: 'BR', name: 'Brazil', flag: Br },
	IO: { iso: 'IO', name: 'British Indian Ocean Territory', flag: Io },
	BN: { iso: 'BN', name: 'Brunei Darussalam', flag: Bn },
	BG: { iso: 'BG', name: 'Bulgaria', flag: Bg },
	BF: { iso: 'BF', name: 'Burkina Faso', flag: Bf },
	BI: { iso: 'BI', name: 'Burundi', flag: Bi },
	CV: { iso: 'CV', name: 'Cabo Verde', flag: Cv },
	KH: { iso: 'KH', name: 'Cambodia', flag: Kh },
	CM: { iso: 'CM', name: 'Cameroon', flag: Cm },
	CA: { iso: 'CA', name: 'Canada', flag: Ca },
	KY: { iso: 'KY', name: 'Cayman Islands', flag: Ky },
	CF: { iso: 'CF', name: 'Central African Republic', flag: Cf },
	TD: { iso: 'TD', name: 'Chad', flag: Td },
	CL: { iso: 'CL', name: 'Chile', flag: Cl },
	CN: { iso: 'CN', name: 'China', flag: Cn },
	CX: { iso: 'CX', name: 'Christmas Island', flag: Cx },
	CC: { iso: 'CC', name: 'Cocos (Keeling) Islands', flag: Cc },
	CO: { iso: 'CO', name: 'Colombia', flag: Co },
	KM: { iso: 'KM', name: 'Comoros', flag: Km },
	CG: { iso: 'CG', name: 'Congo', flag: Cg },
	CD: { iso: 'CD', name: 'Congo, Democratic Republic of the', flag: Cd },
	CK: { iso: 'CK', name: 'Cook Islands', flag: Ck },
	CR: { iso: 'CR', name: 'Costa Rica', flag: Cr },
	HR: { iso: 'HR', name: 'Croatia', flag: Hr },
	CU: { iso: 'CU', name: 'Cuba', flag: Cu },
	CW: { iso: 'CW', name: 'Curaçao', flag: Cw },
	CY: { iso: 'CY', name: 'Cyprus', flag: Cy },
	CZ: { iso: 'CZ', name: 'Czech Republic', flag: Cz },
	CI: { iso: 'CI', name: "Côte d'Ivoire", flag: Ci },
	DK: { iso: 'DK', name: 'Denmark', flag: Dk },
	DJ: { iso: 'DJ', name: 'Djibouti', flag: Dj },
	DM: { iso: 'DM', name: 'Dominica', flag: Dm },
	DO: { iso: 'DO', name: 'Dominican Republic', flag: Do },
	EC: { iso: 'EC', name: 'Ecuador', flag: Ec },
	EG: { iso: 'EG', name: 'Egypt', flag: Eg },
	SV: { iso: 'SV', name: 'El Salvador', flag: Sv },
	GQ: { iso: 'GQ', name: 'Equatorial Guinea', flag: Gq },
	ER: { iso: 'ER', name: 'Eritrea', flag: Er },
	EE: { iso: 'EE', name: 'Estonia', flag: Ee },
	SZ: { iso: 'SZ', name: 'Eswatini', flag: Sz },
	ET: { iso: 'ET', name: 'Ethiopia', flag: Et },
	FK: { iso: 'FK', name: 'Falkland Islands (Malvinas)', flag: Fk },
	FO: { iso: 'FO', name: 'Faroe Islands', flag: Fo },
	FJ: { iso: 'FJ', name: 'Fiji', flag: Fj },
	FI: { iso: 'FI', name: 'Finland', flag: Fi },
	FR: { iso: 'FR', name: 'France', flag: Fr },
	GF: { iso: 'GF', name: 'French Guiana', flag: Gf },
	PF: { iso: 'PF', name: 'French Polynesia', flag: Pf },
	TF: { iso: 'TF', name: 'French Southern Territories', flag: Tf },
	GA: { iso: 'GA', name: 'Gabon', flag: Ga },
	GM: { iso: 'GM', name: 'Gambia', flag: Gm },
	GE: { iso: 'GE', name: 'Georgia', flag: Ge },
	DE: { iso: 'DE', name: 'Germany', flag: De },
	GH: { iso: 'GH', name: 'Ghana', flag: Gh },
	GI: { iso: 'GI', name: 'Gibraltar', flag: Gi },
	GR: { iso: 'GR', name: 'Greece', flag: Gr },
	GL: { iso: 'GL', name: 'Greenland', flag: Gl },
	GD: { iso: 'GD', name: 'Grenada', flag: Gd },
	GP: { iso: 'GP', name: 'Guadeloupe', flag: Gp },
	GU: { iso: 'GU', name: 'Guam', flag: Gu },
	GT: { iso: 'GT', name: 'Guatemala', flag: Gt },
	GG: { iso: 'GG', name: 'Guernsey', flag: Gg },
	GN: { iso: 'GN', name: 'Guinea', flag: Gn },
	GW: { iso: 'GW', name: 'Guinea-Bissau', flag: Gw },
	GY: { iso: 'GY', name: 'Guyana', flag: Gy },
	HT: { iso: 'HT', name: 'Haiti', flag: Ht },
	HM: { iso: 'HM', name: 'Heard Island and McDonald Islands', flag: Hm },
	VA: { iso: 'VA', name: 'Holy See', flag: Va },
	HN: { iso: 'HN', name: 'Honduras', flag: Hn },
	HK: { iso: 'HK', name: 'Hong Kong', flag: Hk },
	HU: { iso: 'HU', name: 'Hungary', flag: Hu },
	IS: { iso: 'IS', name: 'Iceland', flag: Is },
	IN: { iso: 'IN', name: 'India', flag: In },
	ID: { iso: 'ID', name: 'Indonesia', flag: Id },
	IR: { iso: 'IR', name: 'Iran', flag: Ir },
	IQ: { iso: 'IQ', name: 'Iraq', flag: Iq },
	IE: { iso: 'IE', name: 'Ireland', flag: Ie },
	IM: { iso: 'IM', name: 'Isle of Man', flag: Im },
	IL: { iso: 'IL', name: 'Israel', flag: Il },
	IT: { iso: 'IT', name: 'Italy', flag: It },
	JM: { iso: 'JM', name: 'Jamaica', flag: Jm },
	JP: { iso: 'JP', name: 'Japan', flag: Jp },
	JE: { iso: 'JE', name: 'Jersey', flag: Je },
	JO: { iso: 'JO', name: 'Jordan', flag: Jo },
	KZ: { iso: 'KZ', name: 'Kazakhstan', flag: Kz },
	KE: { iso: 'KE', name: 'Kenya', flag: Ke },
	KI: { iso: 'KI', name: 'Kiribati', flag: Ki },
	KP: { iso: 'KP', name: "Korea, Democratic People's Republic of", flag: Kp },
	KR: { iso: 'KR', name: 'Korea, Republic of', flag: Kr },
	KW: { iso: 'KW', name: 'Kuwait', flag: Kw },
	KG: { iso: 'KG', name: 'Kyrgyzstan', flag: Kg },
	LA: { iso: 'LA', name: "Lao People's Democratic Republic", flag: La },
	LV: { iso: 'LV', name: 'Latvia', flag: Lv },
	LB: { iso: 'LB', name: 'Lebanon', flag: Lb },
	LS: { iso: 'LS', name: 'Lesotho', flag: Ls },
	LR: { iso: 'LR', name: 'Liberia', flag: Lr },
	LY: { iso: 'LY', name: 'Libya', flag: Ly },
	LI: { iso: 'LI', name: 'Liechtenstein', flag: Li },
	LT: { iso: 'LT', name: 'Lithuania', flag: Lt },
	LU: { iso: 'LU', name: 'Luxembourg', flag: Lu },
	MO: { iso: 'MO', name: 'Macao', flag: Mo },
	MG: { iso: 'MG', name: 'Madagascar', flag: Mg },
	MW: { iso: 'MW', name: 'Malawi', flag: Mw },
	MY: { iso: 'MY', name: 'Malaysia', flag: My },
	MV: { iso: 'MV', name: 'Maldives', flag: Mv },
	ML: { iso: 'ML', name: 'Mali', flag: Ml },
	MT: { iso: 'MT', name: 'Malta', flag: Mt },
	MH: { iso: 'MH', name: 'Marshall Islands', flag: Mh },
	MQ: { iso: 'MQ', name: 'Martinique', flag: Mq },
	MR: { iso: 'MR', name: 'Mauritania', flag: Mr },
	MU: { iso: 'MU', name: 'Mauritius', flag: Mu },
	YT: { iso: 'YT', name: 'Mayotte', flag: Yt },
	MX: { iso: 'MX', name: 'Mexico', flag: Mx },
	FM: { iso: 'FM', name: 'Micronesia, Federated States of', flag: Fm },
	MD: { iso: 'MD', name: 'Moldova', flag: Md },
	MC: { iso: 'MC', name: 'Monaco', flag: Mc },
	MN: { iso: 'MN', name: 'Mongolia', flag: Mn },
	ME: { iso: 'ME', name: 'Montenegro', flag: Me },
	MS: { iso: 'MS', name: 'Montserrat', flag: Ms },
	MA: { iso: 'MA', name: 'Morocco', flag: Ma },
	MZ: { iso: 'MZ', name: 'Mozambique', flag: Mz },
	MM: { iso: 'MM', name: 'Myanmar', flag: Mm },
	NA: { iso: 'NA', name: 'Namibia', flag: Na },
	NR: { iso: 'NR', name: 'Nauru', flag: Nr },
	NP: { iso: 'NP', name: 'Nepal', flag: Np },
	NL: { iso: 'NL', name: 'Netherlands', flag: Nl },
	NC: { iso: 'NC', name: 'New Caledonia', flag: Nc },
	NZ: { iso: 'NZ', name: 'New Zealand', flag: Nz },
	NI: { iso: 'NI', name: 'Nicaragua', flag: Ni },
	NE: { iso: 'NE', name: 'Niger', flag: Ne },
	NG: { iso: 'NG', name: 'Nigeria', flag: Ng },
	NU: { iso: 'NU', name: 'Niue', flag: Nu },
	NF: { iso: 'NF', name: 'Norfolk Island', flag: Nf },
	MP: { iso: 'MP', name: 'Northern Mariana Islands', flag: Mp },
	NO: { iso: 'NO', name: 'Norway', flag: No },
	OM: { iso: 'OM', name: 'Oman', flag: Om },
	PK: { iso: 'PK', name: 'Pakistan', flag: Pk },
	PW: { iso: 'PW', name: 'Palau', flag: Pw },
	PS: { iso: 'PS', name: 'Palestine, State of', flag: Ps },
	PA: { iso: 'PA', name: 'Panama', flag: Pa },
	PG: { iso: 'PG', name: 'Papua New Guinea', flag: Pg },
	PY: { iso: 'PY', name: 'Paraguay', flag: Py },
	PE: { iso: 'PE', name: 'Peru', flag: Pe },
	PH: { iso: 'PH', name: 'Philippines', flag: Ph },
	PN: { iso: 'PN', name: 'Pitcairn', flag: Pn },
	PL: { iso: 'PL', name: 'Poland', flag: Pl },
	PT: { iso: 'PT', name: 'Portugal', flag: Pt },
	PR: { iso: 'PR', name: 'Puerto Rico', flag: Pr },
	QA: { iso: 'QA', name: 'Qatar', flag: Qa },
	MK: { iso: 'MK', name: 'Republic of North Macedonia', flag: Mk },
	RO: { iso: 'RO', name: 'Romania', flag: Ro },
	RU: { iso: 'RU', name: 'Russian Federation', flag: Ru },
	RW: { iso: 'RW', name: 'Rwanda', flag: Rw },
	RE: { iso: 'RE', name: 'Réunion', flag: Re },
	BL: { iso: 'BL', name: 'Saint Barthélemy', flag: Bl },
	SH: { iso: 'SH', name: 'Saint Helena, Ascension and Tristan da Cunha', flag: Sh },
	KN: { iso: 'KN', name: 'Saint Kitts and Nevis', flag: Kn },
	LC: { iso: 'LC', name: 'Saint Lucia', flag: Lc },
	MF: { iso: 'MF', name: 'Saint Martin (French part)', flag: Mf },
	PM: { iso: 'PM', name: 'Saint Pierre and Miquelon', flag: Pm },
	VC: { iso: 'VC', name: 'Saint Vincent and the Grenadines', flag: Vc },
	WS: { iso: 'WS', name: 'Samoa', flag: Ws },
	SM: { iso: 'SM', name: 'San Marino', flag: Sm },
	ST: { iso: 'ST', name: 'Sao Tome and Principe', flag: St },
	SA: { iso: 'SA', name: 'Saudi Arabia', flag: Sa },
	SN: { iso: 'SN', name: 'Senegal', flag: Sn },
	RS: { iso: 'RS', name: 'Serbia', flag: Rs },
	SC: { iso: 'SC', name: 'Seychelles', flag: Sc },
	SL: { iso: 'SL', name: 'Sierra Leone', flag: Sl },
	SG: { iso: 'SG', name: 'Singapore', flag: Sg },
	SX: { iso: 'SX', name: 'Sint Maarten (Dutch part)', flag: Sx },
	SK: { iso: 'SK', name: 'Slovakia', flag: Sk },
	SI: { iso: 'SI', name: 'Slovenia', flag: Si },
	SB: { iso: 'SB', name: 'Solomon Islands', flag: Sb },
	SO: { iso: 'SO', name: 'Somalia', flag: So },
	ZA: { iso: 'ZA', name: 'South Africa', flag: Za },
	GS: { iso: 'GS', name: 'South Georgia and the South Sandwich Islands', flag: Gs },
	SS: { iso: 'SS', name: 'South Sudan', flag: Ss },
	ES: { iso: 'ES', name: 'Spain', flag: Es },
	LK: { iso: 'LK', name: 'Sri Lanka', flag: Lk },
	SD: { iso: 'SD', name: 'Sudan', flag: Sd },
	SR: { iso: 'SR', name: 'Suriname', flag: Sr },
	SJ: { iso: 'SJ', name: 'Svalbard and Jan Mayen', flag: Sj },
	SE: { iso: 'SE', name: 'Sweden', flag: Se },
	CH: { iso: 'CH', name: 'Switzerland', flag: Ch },
	SY: { iso: 'SY', name: 'Syrian Arab Republic', flag: Sy },
	TW: { iso: 'TW', name: 'Taiwan, Province of China', flag: Tw },
	TJ: { iso: 'TJ', name: 'Tajikistan', flag: Tj },
	TZ: { iso: 'TZ', name: 'Tanzania, United Republic of', flag: Tz },
	TH: { iso: 'TH', name: 'Thailand', flag: Th },
	TL: { iso: 'TL', name: 'Timor-Leste', flag: Tl },
	TG: { iso: 'TG', name: 'Togo', flag: Tg },
	TK: { iso: 'TK', name: 'Tokelau', flag: Tk },
	TO: { iso: 'TO', name: 'Tonga', flag: To },
	TT: { iso: 'TT', name: 'Trinidad and Tobago', flag: Tt },
	TN: { iso: 'TN', name: 'Tunisia', flag: Tn },
	TR: { iso: 'TR', name: 'Turkey', flag: Tr },
	TM: { iso: 'TM', name: 'Turkmenistan', flag: Tm },
	TC: { iso: 'TC', name: 'Turks and Caicos Islands', flag: Tc },
	TV: { iso: 'TV', name: 'Tuvalu', flag: Tv },
	UG: { iso: 'UG', name: 'Uganda', flag: Ug },
	UA: { iso: 'UA', name: 'Ukraine', flag: Ua },
	AE: { iso: 'AE', name: 'United Arab Emirates', flag: Ae },
	GB: { iso: 'GB', name: 'United Kingdom', flag: Gb },
	US: { iso: 'US', name: 'United States', flag: Us },
	UM: { iso: 'UM', name: 'United States Minor Outlying Islands', flag: Um },
	UY: { iso: 'UY', name: 'Uruguay', flag: Uy },
	UZ: { iso: 'UZ', name: 'Uzbekistan', flag: Uz },
	VU: { iso: 'VU', name: 'Vanuatu', flag: Vu },
	VE: { iso: 'VE', name: 'Venezuela', flag: Ve },
	VN: { iso: 'VN', name: 'Viet Nam', flag: Vn },
	VG: { iso: 'VG', name: 'Virgin Islands (British)', flag: Vg },
	VI: { iso: 'VI', name: 'Virgin Islands (U.S.)', flag: Vi },
	WF: { iso: 'WF', name: 'Wallis and Futuna', flag: Wf },
	EH: { iso: 'EH', name: 'Western Sahara', flag: Eh },
	YE: { iso: 'YE', name: 'Yemen', flag: Ye },
	ZM: { iso: 'ZM', name: 'Zambia', flag: Zm },
	ZW: { iso: 'ZW', name: 'Zimbabwe', flag: Zw }
};

const COUNTRY_BY_TIMEZONE_MAP: Record<string, Country> = {
	// Africa
	'Africa/Algiers': COUNTRY_BY_ISO_MAP['DZ'],
	'Africa/Luanda': COUNTRY_BY_ISO_MAP['AO'],
	'Africa/Porto-Novo': COUNTRY_BY_ISO_MAP['BJ'],
	'Africa/Gaborone': COUNTRY_BY_ISO_MAP['BW'],
	'Africa/Ouagadougou': COUNTRY_BY_ISO_MAP['BF'],
	'Africa/Bujumbura': COUNTRY_BY_ISO_MAP['BI'],
	'Africa/Douala': COUNTRY_BY_ISO_MAP['CM'],
	'Atlantic/Cape_Verde': COUNTRY_BY_ISO_MAP['CV'],
	'Africa/Bangui': COUNTRY_BY_ISO_MAP['CF'],
	'Africa/Ndjamena': COUNTRY_BY_ISO_MAP['TD'],
	'Indian/Comoro': COUNTRY_BY_ISO_MAP['KM'],
	'Africa/Brazzaville': COUNTRY_BY_ISO_MAP['CG'],
	'Africa/Kinshasa': COUNTRY_BY_ISO_MAP['CD'],
	'Africa/Lubumbashi': COUNTRY_BY_ISO_MAP['CD'],
	'Africa/Djibouti': COUNTRY_BY_ISO_MAP['DJ'],
	'Africa/Cairo': COUNTRY_BY_ISO_MAP['EG'],
	'Africa/Malabo': COUNTRY_BY_ISO_MAP['GQ'],
	'Africa/Asmara': COUNTRY_BY_ISO_MAP['ER'],
	'Africa/Addis_Ababa': COUNTRY_BY_ISO_MAP['ET'],
	'Africa/Libreville': COUNTRY_BY_ISO_MAP['GA'],
	'Africa/Banjul': COUNTRY_BY_ISO_MAP['GM'],
	'Africa/Accra': COUNTRY_BY_ISO_MAP['GH'],
	'Africa/Conakry': COUNTRY_BY_ISO_MAP['GN'],
	'Africa/Bissau': COUNTRY_BY_ISO_MAP['GW'],
	'Africa/Abidjan': COUNTRY_BY_ISO_MAP['CI'],
	'Africa/Nairobi': COUNTRY_BY_ISO_MAP['KE'],
	'Africa/Maseru': COUNTRY_BY_ISO_MAP['LS'],
	'Africa/Monrovia': COUNTRY_BY_ISO_MAP['LR'],
	'Africa/Tripoli': COUNTRY_BY_ISO_MAP['LY'],
	'Indian/Antananarivo': COUNTRY_BY_ISO_MAP['MG'],
	'Africa/Blantyre': COUNTRY_BY_ISO_MAP['MW'],
	'Africa/Bamako': COUNTRY_BY_ISO_MAP['ML'],
	'Africa/Nouakchott': COUNTRY_BY_ISO_MAP['MR'],
	'Indian/Mauritius': COUNTRY_BY_ISO_MAP['MU'],
	'Africa/Casablanca': COUNTRY_BY_ISO_MAP['MA'],
	'Africa/Maputo': COUNTRY_BY_ISO_MAP['MZ'],
	'Africa/Windhoek': COUNTRY_BY_ISO_MAP['NA'],
	'Africa/Niamey': COUNTRY_BY_ISO_MAP['NE'],
	'Africa/Lagos': COUNTRY_BY_ISO_MAP['NG'],
	'Africa/Kigali': COUNTRY_BY_ISO_MAP['RW'],
	'Africa/Sao_Tome': COUNTRY_BY_ISO_MAP['ST'],
	'Africa/Dakar': COUNTRY_BY_ISO_MAP['SN'],
	'Indian/Mahe': COUNTRY_BY_ISO_MAP['SC'],
	'Africa/Freetown': COUNTRY_BY_ISO_MAP['SL'],
	'Africa/Mogadishu': COUNTRY_BY_ISO_MAP['SO'],
	'Africa/Johannesburg': COUNTRY_BY_ISO_MAP['ZA'],
	'Africa/Juba': COUNTRY_BY_ISO_MAP['SS'],
	'Africa/Khartoum': COUNTRY_BY_ISO_MAP['SD'],
	'Africa/Mbabane': COUNTRY_BY_ISO_MAP['SZ'],
	'Africa/Dar_es_Salaam': COUNTRY_BY_ISO_MAP['TZ'],
	'Africa/Lome': COUNTRY_BY_ISO_MAP['TG'],
	'Africa/Tunis': COUNTRY_BY_ISO_MAP['TN'],
	'Africa/Kampala': COUNTRY_BY_ISO_MAP['UG'],
	'Africa/Lusaka': COUNTRY_BY_ISO_MAP['ZM'],
	'Africa/Harare': COUNTRY_BY_ISO_MAP['ZW'],

	// North America
	'America/Anchorage': COUNTRY_BY_ISO_MAP['US'],
	'America/Los_Angeles': COUNTRY_BY_ISO_MAP['US'],
	'America/Denver': COUNTRY_BY_ISO_MAP['US'],
	'America/Chicago': COUNTRY_BY_ISO_MAP['US'],
	'America/New_York': COUNTRY_BY_ISO_MAP['US'],
	'America/Phoenix': COUNTRY_BY_ISO_MAP['US'],
	'America/Honolulu': COUNTRY_BY_ISO_MAP['US'],
	'America/Toronto': COUNTRY_BY_ISO_MAP['CA'],
	'America/Vancouver': COUNTRY_BY_ISO_MAP['CA'],
	'America/Montreal': COUNTRY_BY_ISO_MAP['CA'],
	'America/Winnipeg': COUNTRY_BY_ISO_MAP['CA'],
	'America/Halifax': COUNTRY_BY_ISO_MAP['CA'],
	'America/Mexico_City': COUNTRY_BY_ISO_MAP['MX'],
	'America/Cancun': COUNTRY_BY_ISO_MAP['MX'],
	'America/Monterrey': COUNTRY_BY_ISO_MAP['MX'],
	'America/Guatemala_City': COUNTRY_BY_ISO_MAP['GT'],
	'America/Panama_City': COUNTRY_BY_ISO_MAP['PA'],
	'America/San_Salvador': COUNTRY_BY_ISO_MAP['SV'],
	'America/Tegucigalpa': COUNTRY_BY_ISO_MAP['HN'],
	'America/Managua': COUNTRY_BY_ISO_MAP['NI'],
	'America/Santo_Domingo': COUNTRY_BY_ISO_MAP['DO'],
	'America/Port_au_Prince': COUNTRY_BY_ISO_MAP['HT'],
	'America/Kingston': COUNTRY_BY_ISO_MAP['JM'],
	'America/Nassau': COUNTRY_BY_ISO_MAP['BS'],
	'America/Bridgetown': COUNTRY_BY_ISO_MAP['BB'],

	// South America
	'America/Sao_Paulo': COUNTRY_BY_ISO_MAP['BR'],
	'America/Rio_Branco': COUNTRY_BY_ISO_MAP['BR'],
	'America/Manaus': COUNTRY_BY_ISO_MAP['BR'],
	'America/Belem': COUNTRY_BY_ISO_MAP['BR'],
	'America/Fortaleza': COUNTRY_BY_ISO_MAP['BR'],
	'America/Recife': COUNTRY_BY_ISO_MAP['BR'],
	'America/Salvador': COUNTRY_BY_ISO_MAP['BR'],
	'America/Buenos_Aires': COUNTRY_BY_ISO_MAP['AR'],
	'America/Cordoba': COUNTRY_BY_ISO_MAP['AR'],
	'America/Mendoza': COUNTRY_BY_ISO_MAP['AR'],
	'America/Santiago': COUNTRY_BY_ISO_MAP['CL'],
	'America/Bogota': COUNTRY_BY_ISO_MAP['CO'],
	'America/Lima': COUNTRY_BY_ISO_MAP['PE'],
	'America/Caracas': COUNTRY_BY_ISO_MAP['VE'],
	'America/La_Paz': COUNTRY_BY_ISO_MAP['BO'],
	'America/Asuncion': COUNTRY_BY_ISO_MAP['PY'],
	'America/Montevideo': COUNTRY_BY_ISO_MAP['UY'],
	'America/Cayenne': COUNTRY_BY_ISO_MAP['GF'],

	// Europe
	'Europe/London': COUNTRY_BY_ISO_MAP['GB'],
	'Europe/Dublin': COUNTRY_BY_ISO_MAP['IE'],
	'Europe/Paris': COUNTRY_BY_ISO_MAP['FR'],
	'Europe/Berlin': COUNTRY_BY_ISO_MAP['DE'],
	'Europe/Rome': COUNTRY_BY_ISO_MAP['IT'],
	'Europe/Madrid': COUNTRY_BY_ISO_MAP['ES'],
	'Europe/Lisbon': COUNTRY_BY_ISO_MAP['PT'],
	'Europe/Moscow': COUNTRY_BY_ISO_MAP['RU'],
	'Europe/Warsaw': COUNTRY_BY_ISO_MAP['PL'],
	'Europe/Prague': COUNTRY_BY_ISO_MAP['CZ'],
	'Europe/Vienna': COUNTRY_BY_ISO_MAP['AT'],
	'Europe/Brussels': COUNTRY_BY_ISO_MAP['BE'],
	'Europe/Amsterdam': COUNTRY_BY_ISO_MAP['NL'],
	'Europe/Athens': COUNTRY_BY_ISO_MAP['GR'],
	'Europe/Helsinki': COUNTRY_BY_ISO_MAP['FI'],
	'Europe/Stockholm': COUNTRY_BY_ISO_MAP['SE'],
	'Europe/Oslo': COUNTRY_BY_ISO_MAP['NO'],
	'Europe/Copenhagen': COUNTRY_BY_ISO_MAP['DK'],
	'Europe/Zurich': COUNTRY_BY_ISO_MAP['CH'],
	'Europe/Bucharest': COUNTRY_BY_ISO_MAP['RO'],
	'Europe/Sofia': COUNTRY_BY_ISO_MAP['BG'],
	'Europe/Belgrade': COUNTRY_BY_ISO_MAP['RS'],

	// Asia
	'Asia/Tokyo': COUNTRY_BY_ISO_MAP['JP'],
	'Asia/Seoul': COUNTRY_BY_ISO_MAP['KR'],
	'Asia/Shanghai': COUNTRY_BY_ISO_MAP['CN'],
	'Asia/Hong_Kong': COUNTRY_BY_ISO_MAP['HK'],
	'Asia/Singapore': COUNTRY_BY_ISO_MAP['SG'],
	'Asia/Kuala_Lumpur': COUNTRY_BY_ISO_MAP['MY'],
	'Asia/Bangkok': COUNTRY_BY_ISO_MAP['TH'],
	'Asia/Jakarta': COUNTRY_BY_ISO_MAP['ID'],
	'Asia/Manila': COUNTRY_BY_ISO_MAP['PH'],
	'Asia/Taipei': COUNTRY_BY_ISO_MAP['TW'],
	'Asia/Dubai': COUNTRY_BY_ISO_MAP['AE'],
	'Asia/Riyadh': COUNTRY_BY_ISO_MAP['SA'],
	'Asia/Kolkata': COUNTRY_BY_ISO_MAP['IN'],
	'Asia/Dhaka': COUNTRY_BY_ISO_MAP['BD'],
	'Asia/Islamabad': COUNTRY_BY_ISO_MAP['PK'],
	'Asia/Tashkent': COUNTRY_BY_ISO_MAP['UZ'],
	'Asia/Almaty': COUNTRY_BY_ISO_MAP['KZ'],
	'Asia/Kabul': COUNTRY_BY_ISO_MAP['AF'],
	'Asia/Yerevan': COUNTRY_BY_ISO_MAP['AM'],
	'Asia/Baku': COUNTRY_BY_ISO_MAP['AZ'],
	'Asia/Beirut': COUNTRY_BY_ISO_MAP['LB'],
	'Asia/Damascus': COUNTRY_BY_ISO_MAP['SY'],
	'Asia/Amman': COUNTRY_BY_ISO_MAP['JO'],
	'Asia/Baghdad': COUNTRY_BY_ISO_MAP['IQ'],
	'Asia/Tehran': COUNTRY_BY_ISO_MAP['IR'],
	'Asia/Jerusalem': COUNTRY_BY_ISO_MAP['IL'],

	// Oceania
	'Australia/Sydney': COUNTRY_BY_ISO_MAP['AU'],
	'Australia/Melbourne': COUNTRY_BY_ISO_MAP['AU'],
	'Australia/Brisbane': COUNTRY_BY_ISO_MAP['AU'],
	'Australia/Perth': COUNTRY_BY_ISO_MAP['AU'],
	'Australia/Adelaide': COUNTRY_BY_ISO_MAP['AU'],
	'Australia/Darwin': COUNTRY_BY_ISO_MAP['AU'],
	'Pacific/Auckland': COUNTRY_BY_ISO_MAP['NZ'],
	'Pacific/Honolulu': COUNTRY_BY_ISO_MAP['US'],
	'Pacific/Guam': COUNTRY_BY_ISO_MAP['GU'],
	'Pacific/Port_Moresby': COUNTRY_BY_ISO_MAP['PG'],
	'Pacific/Noumea': COUNTRY_BY_ISO_MAP['NC'],
	'Pacific/Fiji': COUNTRY_BY_ISO_MAP['FJ'],
	'Pacific/Tahiti': COUNTRY_BY_ISO_MAP['PF'],

	// Additional timezones
	'Atlantic/Reykjavik': COUNTRY_BY_ISO_MAP['IS'],
	'Indian/Maldives': COUNTRY_BY_ISO_MAP['MV']
};

export function getCurrentCountry() {
	const timezone = Intl.DateTimeFormat().resolvedOptions().timeZone;
	const country = COUNTRY_BY_TIMEZONE_MAP[timezone];
	return country;
}

export function getCountryByIso(iso: string | null | undefined) {
	if (!iso) return null;

	const country = COUNTRY_BY_ISO_MAP[iso];
	return country;
}

export function getCountries() {
	return Object.values(COUNTRY_BY_ISO_MAP);
}
