version: 2.1
executors:
  node-executor:
    docker:
      - image: cimg/node:20.10
jobs:
  build-and-deploy:
    executor: node-executor
    environment:
      AWS_REGION: "us-east-1"
    steps:
      - checkout
      - run:
          name: Install AWS CLI
          command: |
            sudo apt-get update
            sudo apt-get install -y awscli
      - run:
          name: Clean install
          command: |
            rm -rf node_modules package-lock.json
            npm install
      - run:
          name: Install Rollup dependencies
          command: |
            npm install -D @rollup/rollup-linux-x64-gnu
      - run:
          name: Install static adapter
          command: |
            npm install -D @sveltejs/adapter-static
      - run:
          name: Update svelte.config.js
          command: |
            # Backup original config
            cp svelte.config.js svelte.config.js.bak
            
            # Replace adapter-auto with adapter-static
            sed -i 's/@sveltejs\/adapter-auto/@sveltejs\/adapter-static/g' svelte.config.js
            
            # Update adapter configuration
            sed -i "s/adapter())/adapter({\n\t\tpages: 'build',\n\t\tassets: 'build',\n\t\tfallback: 'index.html',\n\t\tprecompress: true\n\t}))/g" svelte.config.js
            
            # Show the updated file
            cat svelte.config.js
      - run:
          name: SvelteKit sync step
          command: |
            npx svelte-kit sync
      - run:
          name: Create missing component
          command: |
            # Create directories if they don't exist
            mkdir -p src/lib/components/sidebar
            
            # Create a placeholder sidebar component
            echo '<script>
            // Placeholder sidebar component for build
            </script>

            <div class="sidebar-placeholder">
              <!-- This is a placeholder sidebar component created during CI build -->
            </div>' > src/lib/components/sidebar/Sidebar.svelte
      - run:
          name: Build the SvelteKit project
          command: |
            npm run build
      - run:
          name: Configure AWS CLI with environment variables
          command: |
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws configure set default.region us-east-1
      - run:
          name: Sync static files to S3 bucket
          command: |
            aws s3 sync ./build s3://yautomator-frontend --delete
      - run:
          name: Invalidate CloudFront cache
          command: |
            aws cloudfront create-invalidation \
              --distribution-id E36ORJ42Z47UJ4 \
              --paths "/*"
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-and-deploy