version: 2.1
executors:
  node-executor:
    docker:
      - image: cimg/node:20.5
jobs:
  build-and-deploy:
    executor: node-executor
    environment:
      AWS_REGION: "us-east-1"
    steps:
      - checkout
      - run:
          name: Install AWS CLI
          command: |
            sudo apt-get update
            sudo apt-get install -y awscli
      - run:
          name: Install dependencies
          command: |
            npm install
      - run:
          name: Install static adapter
          command: |
            npm install -D @sveltejs/adapter-static
      - run:
          name: Build the SvelteKit project
          command: |
            npm run build
      - run:
          name: Configure AWS CLI with environment variables
          command: |
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws configure set default.region us-east-1
      - run:
          name: Sync static files to S3 bucket
          command: |
            aws s3 sync ./build s3://yautomator-frontend --delete
      - run:
          name: Invalidate CloudFront cache
          command: |
            aws cloudfront create-invalidation \
              --distribution-id E36ORJ42Z47UJ4 \
              --paths "/*"
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-and-deploy