version: 2.1
executors:
  node-executor:
    docker:
      - image: cimg/node:20.10
jobs:
  build-and-deploy:
    executor: node-executor
    environment:
      AWS_REGION: "us-east-1"
    steps:
      - checkout
      - run:
          name: Install AWS CLI
          command: |
            sudo apt-get update
            sudo apt-get install -y awscli
      - run:
          name: Clean install
          command: |
            rm -rf node_modules package-lock.json
            npm install
      - run:
          name: Install Rollup dependencies
          command: |
            npm install -D @rollup/rollup-linux-x64-gnu @sveltejs/adapter-static
      - run:
          name: Create essential directories
          command: |
            mkdir -p .svelte-kit
            echo '{
              "compilerOptions": {
                "baseUrl": "..",
                "paths": {
                  "$lib": ["src/lib"],
                  "$lib/*": ["src/lib/*"]
                }
              }
            }' > .svelte-kit/tsconfig.json
      - run:
          name: Pre-build actions
          command: |
            # Temporarily move problematic files
            mkdir -p .temp_backup
            echo "Moving problematic route files..."
            mv src/routes/startup .temp_backup/ || echo "startup directory not found"
            
            # Create empty directory to prevent errors
            mkdir -p src/routes/startup
            touch src/routes/startup/.gitkeep
            
            # Prepare svelte.config.js for static build
            cp svelte.config.js svelte.config.js.bak
            echo 'import adapter from "@sveltejs/adapter-static";
            import { vitePreprocess } from "@sveltejs/vite-plugin-svelte";

            /** @type {import("@sveltejs/kit").Config} */
            const config = {
              preprocess: vitePreprocess(),
              kit: {
                adapter: adapter({
                  pages: "build",
                  assets: "build",
                  fallback: "index.html",
                  prerender: false
                })
              }
            };

            export default config;' > svelte.config.js
      - run:
          name: Build client-only app
          command: |
            npx svelte-kit sync
            npm run build
      - run:
          name: Configure AWS CLI with environment variables
          command: |
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws configure set default.region us-east-1
      - run:
          name: Sync static files to S3 bucket
          command: |
            aws s3 sync ./build s3://yautomator-frontend --delete
      - run:
          name: Invalidate CloudFront cache
          command: |
            aws cloudfront create-invalidation \
              --distribution-id E36ORJ42Z47UJ4 \
              --paths "/*"
      - run:
          name: Restore original files
          command: |
            mv svelte.config.js.bak svelte.config.js || echo "No backup found"
            # We don't restore the problematic routes to avoid git diff
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-and-deploy